---
apiVersion: build.knative.dev/v1alpha1
kind: Build
metadata:
  name: 'example-build'
spec:
  serviceAccountName: build-auth-example
  source:
    git:
      url: https://github.com/example/build-example.git
      revision: master
  steps:
  - name: ubuntu-example
    image: ubuntu
    args: ["ubuntu-build-example", "SECRETS-example.md"]
  - name: build-example
    image: gcr.io/example-builders/build-example
    args: ['echo', 'hello-example', 'build']
